export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILURE = "AUTH_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_RESET = "AUTH_RESET";

export const SETTINGS_CHANGE_USERNAME_START = "SETTINGS_CHANGE_USERNAME_START";
export const SETTINGS_CHANGE_USERNAME_SUCCESS = "SETTINGS_CHANGE_USERNAME_SUCCESS";
export const SETTINGS_CHANGE_USERNAME_FAILURE = "SETTINGS_CHANGE_USERNAME_FAILURE";
export const SETTINGS_CHANGE_USERNAME_RESET = "SETTINGS_CHANGE_USERNAME_RESET";
export const SETTINGS_CHANGE_PASSWORD_START = "SETTINGS_CHANGE_USERNAME_START";
export const SETTINGS_CHANGE_PASSWORD_SUCCESS = "SETTINGS_CHANGE_PASSWORD_SUCCESS";
export const SETTINGS_CHANGE_PASSWORD_FAILURE = "SETTINGS_CHANGE_PASSWORD_FAILURE";
export const SETTINGS_CHANGE_PASSWORD_RESET = "SETTINGS_CHANGE_PASSWORD_RESET";

export const SURVEY_LIST_START = "SURVEY_LIST_START";
export const SURVEY_LIST_SUCCESS = "SURVEY_LIST_SUCCESS";
export const SURVEY_LIST_FAILURE = "SURVEY_LIST_FAILURE";
export const SURVEY_LIST_RESET = "SURVEY_LIST_RESET";

export const SURVEY_DETAILS_START = "SURVEY_DETAILS_START";
export const SURVEY_DETAILS_SUCCESS = "SURVEY_DETAILS_SUCCESS";
export const SURVEY_DETAILS_FAILURE = "SURVEY_DETAILS_FAILURE";
export const SURVEY_DETAILS_RESET = "SURVEY_DETAILS_RESET";

export const SURVEY_DELETE_START = "SURVEY_DELETE_START";
export const SURVEY_DELETE_SUCCESS = "SURVEY_DELETE_SUCCESS";
export const SURVEY_DELETE_FAILURE = "SURVEY_DELETE_FAILURE";
export const SURVEY_DELETE_RESET = "SURVEY_DELETE_RESET";

export const SURVEY_CREATE_EDIT_START = "SURVEY_CREATE_EDIT_START";
export const SURVEY_CREATE_EDIT_SUCCESS = "SURVEY_CREATE_EDIT_SUCCESS";
export const SURVEY_CREATE_EDIT_FAILURE = "SURVEY_CREATE_EDIT_FAILURE";
export const SURVEY_CREATE_EDIT_RESET = "SURVEY_CREATE_EDIT_RESET";

export const RESPONSE_DETAILS_START = "RESPONSE_DETAILS_START";
export const RESPONSE_DETAILS_SUCCESS = "RESPONSE_DETAILS_SUCCESS";
export const RESPONSE_DETAILS_FAILURE = "RESPONSE_DETAILS_FAILURE";
export const RESPONSE_DETAILS_RESET = "RESPONSE_DETAILS_RESET";

export const RESPONSE_SUBMIT_START = "RESPONSE_SUBMIT_START";
export const RESPONSE_SUBMIT_SUCCESS = "RESPONSE_SUBMIT_SUCCESS";
export const RESPONSE_SUBMIT_FAILURE = "RESPONSE_SUBMIT_FAILURE";
export const RESPONSE_SUBMIT_RESET = "RESPONSE_SUBMIT_RESET";